version: "3.8"
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - backend-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - backend-network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=yourdatabase
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
    networks:
      - backend-network

networks:
  backend-network:
    external: true
