version: "3.8"

services:
  data-acquisition-service:
    build:
      context: ./data-acquisition-service
      dockerfile: Dockerfile.dev
    volumes:
      - ./data-acquisition-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "6000:6000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - NODE_ENV=development
      - RABBITMQ_HOST=rabbitmq
    command: npm run dev
    depends_on: #it doesn't guarantee RabbitMQ is ready to accept connections.
      - redis
      - rabbitmq
    networks:
      - backend-network

  # trading-strategy-service:
  #   build: ./trading-strategy-service
  #   ports:
  #     - "5001:5001"

  # order-execution-service:
  #   build: ./order-execution-service
  #   ports:
  #     - "5002:5002"

  trading-bot-server:
    build: ./trading-bot-server
    ports:
      - "5003:5003"
    volumes:
      - ./trading-bot-server:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on:
      - redis
      - rabbitmq
      - data-acquisition-service
      # - trading-strategy-service
      # - order-execution-service

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - NODE_ENV=development
      - RABBITMQ_HOST=rabbitmq
      - DATA_ACQUISITION_SERVICE_URL=http://data-acquisition-service:5000
    networks:
      - backend-network

  trading-bot-client:
    build: ./trading-bot-client
    volumes:
      - ./trading-bot-client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - trading-bot-server

networks:
  backend-network:
    name: backend-network
