version: "3.8"

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  data-acquisition-service:
    build: ./data-acquisition-service
    volumes:
      - ./data-acquisition-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "6000:6000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - redis

  # trading-strategy-service:
  #   build: ./trading-strategy-service
  #   ports:
  #     - "5001:5001"

  # order-execution-service:
  #   build: ./order-execution-service
  #   ports:
  #     - "5002:5002"

  client-service:
    build: ./client-service
    ports:
      - "5003:5003"
    volumes:
      - ./client-service:/usr/src/app
    command: npm run dev
    depends_on:
      - data-acquisition-service
      # - trading-strategy-service
      # - order-execution-service
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - NODE_ENV=development
      - DATA_ACQUISITION_SERVICE_URL=http://data-acquisition-service:5000

  # client-app:
  #   build: ./client-app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - client-service
