# Use the official Node.js image as the base
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm ci

# Expose the port on which the service will run
EXPOSE 6000

# Set environment variables (if needed)
ENV NODE_ENV=development

# Run the service in development mode
CMD ["npm", "run", "dev"]